# == Global project settings ===========================================

name:             POSM
attribution:      Data © OpenStreetMap Contributors
center:           [-75.525, 39.158, 12]
format:           png
interactivity:    false
minzoom:          0
maxzoom:          22
scale:            1
metatile:         4
srs:              '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'


# == Layer & Datasource defaults =======================================

_layer_default:   &layer
  'srs-name':     '3857'
  srs:            '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'

_pg_default:      &postgis
  type:           postgis
  dbname:         '{{PGDATABASE}}'
  host:           '{{PGHOST}}'
  user:           '{{PGUSER}}'
  password:       '{{PGPASSWORD}}'
  port:           '{{PGPORT}}'
  geometry_field: way
  srid:           3857
  extent:         '-20037508.34,-20037508.34,20037508.34,20037508.34'
  srs:            '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'

# == Stylesheets =======================================================

Stylesheet:
  - styles.mss


# == Layers ============================================================

Layer:

  - <<: *layer
    name: highway
    id:   highway
    status: on
    Datasource:
      <<: *postgis
      table: >
        (
          SELECT
            *
          FROM planet_osm_roads
          WHERE way && !bbox!
        ) AS data

  - <<: *layer
    name: building
    id:   building
    Datasource:
      <<: *postgis
      table: >
        (
          SELECT
            *
          FROM planet_osm_polygon
          WHERE way && !bbox!
            AND building IS NOT NULL
        ) AS data
